apiVersion: v1
kind: Service
metadata:
  annotations:
    epinio.io/created-by: "user"
  labels:
    app.kubernetes.io/managed-by: epinio
    app.kubernetes.io/part-of: "NAMESPACE"
    helm.sh/chart: epinio-application-traefiked-0.0.4
    app.kubernetes.io/name: "myapp"
    app.kubernetes.io/component: application
  name: rmyapp-94e7d341f71ff6f43253f1c5e813057b22f91cda
  namespace:  "NAMESPACE"
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: "myapp"
    app.kubernetes.io/component: application
  type: ClusterIP
