apiVersion: v2
name: epinio-application-traefiked
description: The helm chart for epinio applications to be deployed by (with traefik native support)
icon: https://raw.githubusercontent.com/epinio/helm-charts/main/assets/epinio.png
home: https://J4NS-R/epinio-app-charts
type: application
version: 0.0.3
keywords:
- epinio
- paas
maintainers: []
sources:
- https://J4NS-R/epinio-app-charts
annotations:
  # Same as upstream fork
  artifacthub.io/license: Apache-2.0
