{{- $cfg := include "epinio-traefik-config" . | fromJson -}}
{{- $seen := dict -}}
{{- range .Values.epinio.routes }}
{{- if not (hasKey $seen .domain) -}}
{{- $_ := set $seen .domain true -}}
{{- $ep := include "epinio-route-entrypoint" (list $cfg .domain) -}}
{{- $tlsOpts := include "epinio-route-traefik-tls-options" (list $cfg .domain) | fromJson -}}
{{- $hasTLS := include "epinio-route-has-tls" (list $ep (empty $tlsOpts)) -}}
{{- if $hasTLS -}}
{{- $ti := include "epinio-route-tls-issuer" (list $cfg .domain) -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "epinio-tls-secret-name" (list $.Values.epinio.appName .domain) }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    {{- include "epinio-application.annotations" $ | nindent 4 }}
  labels:
    {{- include "epinio-application.labels" $ | nindent 4 }}
spec:
  secretName: {{ include "epinio-tls-secret-name" (list $.Values.epinio.appName .domain) }}
  dnsNames:
    - {{ .domain }}
  issuerRef:
    name: {{ $ti }}
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
{{- end }}
{{ end }}