{{- $cfg := include "epinio-traefik-config" . | fromJson -}}
{{- range .Values.epinio.routes }}
{{- $ep := include "epinio-route-traefik-option" (list $cfg .domain "entryPoint") -}}
{{- $cr := include "epinio-route-traefik-option" (list $cfg .domain "certResolver") -}}
{{- $tlsOpts := include "epinio-route-traefik-tls-options" (list $cfg .domain) | fromJson -}}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "epinio-truncate" (print $.Values.epinio.appName "-" .id) }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    {{- include "epinio-application.annotations" $ | nindent 4 }}
  labels:
    {{- include "epinio-application.labels" $ | nindent 4 }}
spec:
  {{- with $.Values.epinio.ingress }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- if not (empty $ep) }}
  entryPoints:
    - {{ $ep | quote }}
  {{- end }}
  routes:
  - match: Host(`{{ .domain }}`) && PathPrefix(`{{ .path }}`)
    kind: Rule
    services:
    - name: {{ include "epinio-app-service-name" $ }}
      port: 8080
  {{- if and (empty $tlsOpts) (empty $cr) }}
  tls: {}
  {{- else }}
  tls:
    {{- if not (empty $tlsOpts) }}
    options:
      {{- with $tlsOpts.name }}
      name: {{ . | quote }}
      {{- end }}
      {{- with $tlsOpts.namespace }}
      namespace: {{ . | quote }}
      {{- end }}
    {{- end }}
    {{- if not (empty $cr) }}
    certResolver: {{ $cr | quote }}
    {{- end }}
  {{- end }}
{{ end }}