{{- range .Values.epinio.routes }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "epinio-truncate" (print $.Values.epinio.appName "-" .id) }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    {{- include "epinio-application.annotations" $ | nindent 4 }}
  labels:
    {{- include "epinio-application.labels" $ | nindent 4 }}
spec:
  {{- with $.Values.epinio.ingress }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- with $.Values.userConfig.traefik }}
  {{- with .entryPoints }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  routes:
  - match: Host(`{{ .domain }}`) && PathPrefix(`{{ .path }}`)
    kind: Rule
    services:
    - name: {{ include "epinio-app-service-name" $ }}
      port: 8080
  tls:
    {{- with $.Values.userConfig.traefik }}
    {{- with .tls }}
    {{- with .options }}
    options:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .certResolver }}
    certResolver: {{ . | quote }}
    {{- end }}
    {{- end }}
    {{- else }}
    {}
    {{- end }}
{{- end }}
