{{- if eq (include "epinio-serviceaccount-enabled" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "epinio-truncate" .Values.epinio.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "epinio-application.labels" . | nindent 4 }}
  annotations:
    {{- include "epinio-application.annotations" . | nindent 4 }}
{{- end }}
