apiVersion: application.epinio.io/v1
kind: AppChart
metadata:
  name: traefiked
spec:
  shortDescription: Traefik-native ingress
  description: Fork of epinio default AppChart with Traefik-native ingressroute
  helmChart: https://github.com/J4NS-R/epinio-app-charts/releases/download/v0.0.4/epinio-application-traefiked-0.0.4.tgz
  settings:
    # See Chart values.yaml for an example
    traefik:
      type: string
